config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'vehicles#show'
  get 'show', to: 'vehicles#show'
  #resources :vehicles
  scope module: 'api', path: "(:api)", api: /api/ , defaults: {format: 'json'} do
    namespace :v1 do
      #get '/gps', to: 'locations#index'
      post '/gps', to: 'locations#create'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :vehicle
  validates :latitude, :longitude, :sent_at, :vehicle_identifier, presence: true

  def long_and_lat
    [self.latitude,self.longitude,self.vehicle_identifier]
  end

  def self.assign_new_location_to_vehicle(location)
    VehicleLocationsWorker.perform_in(1.second, location)
  end

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :locations, dependent: :destroy
  validates_uniqueness_of :identifier
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :new, only: [:create]
  
  def index
  end

  def create
    if @location[:latitude].present? && @location[:longitude].present? && @location[:sent_at].present? && @location[:vehicle_identifier].present?
      #metodo que se ejecutara en background y hara el registro en la bd
      if Location.assign_new_location_to_vehicle(@location)
        render json: {status: 200}
      else
        render json: {errors: "Ocurrió un error al procesar la petición", status: :unprocessable_entity }
      end
    else
      render json: {errors: "Ocurrió un error al procesar la petición, faltan parametros", status: :unprocessable_entity }
    end
  end

  def show
    render json: {vehicle: @vehicle}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :sent_at, :vehicle_identifier, :vehicle_id)
    end

    def new
      @location = {latitude: params[:latitude], longitude: params[:longitude], sent_at: params[:sent_at], vehicle_identifier: params[:vehicle_identifier]}
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show_uniq, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show_uniq
    @address_ar = []
    if @vehicle.locations.present?
      @vehicle.locations.last
        @address_ar.push(@vehicle.locations.order(sent_at: :asc).last.long_and_lat)
    end
  end

  #muestra en el mapa de google con un icono de un vehiculo azul su localización mas reciente
  def show
    @address_ar = []
    @vehicles = Vehicle.all
    @vehicles.each do |vehicle|
      if vehicle.locations.present?
        @address_ar.push(vehicle.locations.order(sent_at: :asc).last.long_and_lat)
      end
    end
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:identifier, :brand)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeetrackApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :identifier %>
    <%= form.text_field :identifier %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.identifier %></td>
        <td><%= vehicle.brand %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Complex Marker Icons</title>
    <style>
      #map {
        height: 100%;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
    var address_ar = <%= raw @address_ar %>;
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 7,
          center: {lat: address_ar[address_ar.length - 1][0], lng: address_ar[address_ar.length - 1][1]}
        });

        setMarkers(map);
      }

      function setMarkers(map) {
        var image = '<%= asset_path("camion.png") %>';
        // Shapes define the clickable region of the icon. The type defines an HTML
        // <area> element 'poly' which traces out a polygon as a series of X,Y points.
        // The final coordinate closes the poly by connecting to the first coordinate.
        var shape = {
          coords: [1, 1, 1, 20, 18, 20, 18, 1],
          type: 'poly'
        };
        for (var i = 0; i < address_ar.length; i++) {
          var z = i+1;
          var address = address_ar[i];
          var marker = new google.maps.Marker({
            position: {lat: address[0], lng: address[1]},
            map: map,
            icon: image,
            shape: shape,
            title:  address[2],
            zIndex: z
          });
        }
      }

    </script>
    <script async defer src=<%="https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}&callback=initMap"%> type="text/javascript">
    </script>

  </body>
</html>